name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 15

      - run: npm install -g npm@7

      - run: node -v
      - run: npm -v

      - run: npm install

      - run: npm install --save-dev prettier

      - run: npm run lint

      - run: npm run prettier

      - run: CI=true npm run test

      - run: npm run build
